apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: ingressgateway
  namespace: istio-system
spec:
  targets:
    - name: istio-ingressgateway
  peers:
    - mtls: {}
  origins:
    - jwt:
        issuer: "https://sergey-onofreichuk.auth0.com/"
        jwksUri: "https://sergey-onofreichuk.auth0.com/.well-known/jwks.json"
  principalBinding: USE_ORIGIN