apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: frontend-policy
spec:
  targets:
    - name: frontend
  peers:
    - mtls: {}
  origins:
    - jwt:
        issuer: "https://dev-e2bwzo-l.eu.auth0.com/"
        jwksUri: "https://dev-e2bwzo-l.eu.auth0.com/.well-known/jwks.json"
  principalBinding: USE_ORIGIN